### ISSUE TITLE
BitmapTextField with zero width and height freezes Chrome

### ISSUE THREAD

**Issue by ryanfields** [vikramarka/createjsbitmaptext#3]
Passing ```0, 0``` for width and height in BitmapTextField freezes the Chrome tab.

While there's no normal use case I can think of for passing a zero size, if it happens as a result of user input or some other weird calculation it results in a lockup.  There's no way to even open the debugging tools to see what's going on.  Can't even close the tab without force-killing Chrome.

**Comment by vikramarka** [comment]
Hi,

Thanks for reporting the issue. I've just committed the fix. Please check.

**Comment by ryanfields** [comment]
Checked it and it works.  Thank you.
